# Generated by Django 5.2.13 on 2026-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('university', 'University'), ('student', 'Student'), ('company', 'Company')], max_length=20, null=True),
        ),
    ]
