# Generated by Django 5.2.13 on 2026-05-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SideNavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(choices=[('dashboard', 'Dashboard'), ('companies', 'Companies'), ('students', 'Students'), ('jobs', 'Job Postings'), ('courses', 'Courses'), ('batches', 'Batches'), ('applications', 'Applications'), ('profile', 'Profile')], max_length=100)),
            ],
        ),
    ]
