# Generated by Django 5.2.13 on 2026-05-04 18:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_skill_remove_job_roles_job_skill_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skill',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
